### ISSUE TITLE
Unit tests fail in 3.9

### ISSUE THREAD

**Issue by alexmorrisnz** [michael-milette/moodle-filter_filtercodes#136]
```
vendor/bin/phpunit "filter_filtercodes_testcase" filter/filtercodes/tests/filter_test.php
Moodle 3.9.3 (Build: 20201109), 13ef9a84dacf2e6d43c330f43b531ccd01874894
Php: 7.2.34.8.18.04.1.1, pgsql: 10.14 (Ubuntu 10.14-0ubuntu0.18.04.1), OS: Linux 5.4.0-52-generic x86_64
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

F                                                                   1 / 1 (100%)

Time: 1.38 seconds, Memory: 42.00 MB

There was 1 failure:

1) filter_filtercodes_testcase::test_filter_filtercodes
Failed asserting that '{Admin}' matches expected null.

/filter/filtercodes/tests/filter_test.php:281
/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
 vendor/bin/phpunit "filter_filtercodes_testcase" filter/filtercodes/tests/filter_test.php

FAILURES!
Tests: 1, Assertions: 18, Failures: 1.
```

I think this is happening because the alternate name isn't set for the admin user in unit tests.

**Comment by alexmorrisnz** [comment]
There's also this:
```
            array (
                'before' => '{fullname}',
                'after'  => $USER->lastname . ' ' . $USER->lastname,
            ),
```
Which should be firstname and lastname, not lastname lastname.

**Comment by michael-milette** [comment]
Hi @alexmorrisnz ,

Thank you very much for reporting these issues. Both of them have been fixed as well as several others. The changes are now available on GitHub and will be included in the upcoming release of FilterCodes on Moodle.org in the coming days.

Best regards,

Michael

**Comment by alexmorrisnz** [comment]
@michael-milette Hi unit tests are still failing, this time on:
```
            array (
                'before' => '{courseshortname}',
                'after'  => $PAGE->course->id == $SITE->id ? $SITE->fullname : $PAGE->course->shortname,
            ),
```
Because you set the page to `/` that if statement there is true and it is using the site fullname which doesn't match with (on 3.9 stable) the sitename of `phpunit`

**Comment by michael-milette** [comment]
Thanks @alexmorrisnz . Fixed.
