### ISSUE TITLE
PHPUnit errors

### ISSUE THREAD

**Issue by ewallah** [michael-milette/moodle-filter_filtercodes#95]
1) coding_exception: Coding error detected, it must be fixed by a programmer: Invalid string identifier. The identifier cannot be empty. Please fix your get_string() call. (32767)
$USER->country can be an empty string

2) Undefined variable: PAGE
You cannot use the global $PAGE variable is you do not define it.

3) Failed asserting that two strings are equal.
-'Some non-filtered content plus some content in French (<span lang="fr">mieux en français</span>)'
+'Some non-filtered content plus some content in French (<span lang="fr">mieux en français)</span>'
The ) is not on the right place

4) Failed asserting that two strings are equal.
-'<span lang="es">Algo en español</span><span lang="fr">Quelque chose en français</span>'
+'<span lang="es">Algo en español{langx}{langx fr}Quelque chose en français</span>'
The filter does not work as expected

5) Failed asserting that two strings are equal.
-'Non-filtered {begin}<span lang="es">Algo en español</span><span lang="fr">Quelque chose en français</span> Non-filtered{end}'
+'Non-filtered {begin}<span lang="es">Algo en español{langx}{langx fr}Quelque chose en français</span>Non-filtered{end}'
The filter does not work as expected

6) Failed asserting that two strings are equal
-'{langx}Bad filter syntax{langx}<span lang="es">Algo en español</span>'
+'{langx}Bad filter syntax{langx}<span lang="es">Algo de español</span>'
'en' does not change into 'de'

....

**Comment by michael-milette** [comment]
Hi @ewallah ,

Thank you for the feedback. These are now fixed however I am working on some additional ones now.

Michael

**Comment by ewallah** [comment]
Hi Michael,

The new test still have issues:  you can see the first failure in your own Travis environment:  https://travis-ci.org/github/michael-milette/moodle-filter_filtercodes/jobs/704647374#L367

All these tests are still failing:

'before' => '{alternatename}', <>   'after'  => $USER->alternatename,
'before' => '{fullname}', <>  'after'  => $USER->lastname . ' ' . $USER->lastname,
'before' => '%7Buserid%7D', <> 'after'  => $USER->id,
'before' => '{course}', <> 'after'  => $course->id,
'before' => '%7Bcourseid%7D', <>  'after'  => $course->id,
'before' => '{coursename}', <> 'after'  => $course->fullname,
'before' => '{courseshortname}', <>  'after'  => $course->shortname,
'before' => '{pagepath}', <>   'after'  => $CFG->wwwroot . '?',
'before' => '{fa fa-icon-name}', <>  'after'  => '<span class="fa-icon-name" aria-hidden="true"></span>',

R

**Comment by michael-milette** [comment]
Hi @ewallah , thanks for the update. I know there is still a bit of a way to go. Everytime I fix some tests, a bunch it comes up. I will continue to work on it until all the tests are working.

Best regards,

Michael

**Comment by michael-milette** [comment]
Hi @ewallah ,

Thank you very much for reporting these issues. All of them have been fixed. The changes are now available on GitHub and will be included in the upcoming release of FilterCodes on Moodle.org in the coming days.

Best regards,

Michael
